#
# Module manifest for module 'PanoDemoDataSync'
#
# Generated by: paulryan
#
# Generated on: 27/09/2023
#

@{

RootModule = 'PanoDemoDataSync.psm1'
ModuleVersion = '1.0.01'
GUID = '18d2b202-5f19-4255-af9b-198b2f9ef163'
Author = 'Paul Ryan'
CompanyName = 'Panoram Digital'
Copyright = '(c) Panoram Digital. All rights reserved.'
FunctionsToExport = '*'
CmdletsToExport = @()
VariablesToExport = '*'
AliasesToExport = @()
PrivateData = @{}

}
